services:
  db:
    image: postgres:16-alpine
    container_name: nutricion_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nutricion
      POSTGRES_USER: nutricion_user
      POSTGRES_PASSWORD: nutricion_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
